apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-pings
    namespace: backup
stringData:
    POSTGRES_DUMP_PING_URL: ENC[AES256_GCM,data:kS8FGm1RCDxY51rlhPPW8/yFogXGZ0j9Md6Fze6t+Acv/GHQps3L9pXNBF0zCylsPr7afJ2S9Z4=,iv:7D8I8RK1qUZInOVak9BIOKQxG+5qIsy289ztiUvRI3c=,tag:gNGBcSWPgULWlsfS6IckFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeWtNVER6Y0tHUUpOUkcy
            eGMrcERueDhEOU1vbHhhVmJUSHAwR2lZWHg0ClowOXVEYkFzaGFrNXVrOXRibEl1
            Y0h4VGtncVhLUjhNVUtsZXd4VGIzVWsKLS0tIHkzYzNqTFB2WVNDcmJJVytQYWE0
            NnhTNG80VDVtaTlON1FoY1VYd2pzKzgKojfwKnHoJM9BudSGdRwuZmpJYP/9mj23
            TffTdAC7ig3eIz8BW/5OBzTTNBOBOZsMJo9oH4bqTOSOdQKoYLpHfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMHE3VkNQZE9US2QrbTBM
            QnRPbG9SMmQxYVBCRVdHdE5vT3EwRURmWDJJCmNEQ1diUUlPUlQxVmllM0V0VHgw
            cEtzRzBteHJYVVQ5SC83Z0ZzWHpuS2MKLS0tIHJvUGx1cHg2Mkg5VzlrdzdOSEQw
            c1VnZU4xaGRsaVd6RG1CYnEwY1grdHcKtT7IeeeZOkkuneUhum8ZE1uBeLpyTByr
            +VYO12219g6ATDdPGBxZNIiFWihmPrGOV1YqW/xlIRB/mFapzJIu/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T07:51:47Z"
    mac: ENC[AES256_GCM,data:bCB2Mh/eBcMOdPrzWAcnwXG1xhsJoJT7Fgc41IrdZZFKg5HmZ93QYxOyuxNhv37mNM7bPJkmljH08bOgAvE3bH5sbsijJsJQ2tfSbGXs6BGEl1rVPK0ySHCbAJ7TwMdHThB2PL5MFNkO/WiU0qRNnk8xP8zzw/NGQIOlPNCvi5g=,iv:JQjQtbPVA1q0CVHBij1ZPB1Gf2v7VsUQfPU0nhqVuX8=,tag:YlP7xYZt+aWxhh0efK11og==,type:str]
    version: 3.13.3
