apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres
    namespace: backup
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:BZWwcs5p,iv:IAJ7B8AsERbpYAvXY2pMl7Yjoe9vVcxPwUzFjVTIAk8=,tag:jndDs5IVIwMccSig/76bVA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MrwJ8Cm9d/B2F++ykedbKwU/YkGvlmaJRCwv0s6sOcg=,iv:+UUIa+42sHd9/D7/uyG6tNMaL+auVbqjeaAmskME4Rw=,tag:beOfs73IiM5uHjGmdMgWFw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ZyebKvFO,iv:l3dcWMuLkAuIJvjLe/gaSMa509QPgSswiFqvglBfGdw=,tag:Q7N84KHFRhndq8aMV9SbXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveG9hdzg0S3pYeTVlc3BY
            dG1UTmdaSUh4YmM4TjhDaDAxNmo1YmowOGhZCitncWZGeWhuVjdHckdmd29pb3Nh
            Mko3Ykh0UGJXaVFEcEJMek9lOWlWdFkKLS0tIHZvRDE5WUorVytIWGRYQ2ZvdzFy
            SEd0Y3p4bTB2d09nK0lFTzlwZzRZZlUKILuErkSyuPo9NeyjChwaV0iunFUUHLyH
            YWDLVtnzuir0pARXNoDs9yO/PizCE04knI0Ru7bhm1KCZGsdgKGbFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRXZMUW9EQXVucDNCSjRp
            RnBJYi8vazZxSitYVXJlTDJjVmRGZUo1NVVFCjNCdUh0ZHV1QjFFai84NDl4WEk0
            dlZDQ2Fab1d2OUJjNk05Wmd2enE3TW8KLS0tIDRFeVlUd3d2LzJNZFNnbDFIRzFr
            QTRZeEdNZ1hGdzhJTzR5VU5IUkRPVmMKI7KKYj6Voy6/A2Tj4uudbSEEkTaOCTkr
            cTVPjTrc23v6h20dyd2Up9o0vsQ6HkujpdjYmWYhpv3K0oHG9KJccA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T07:51:47Z"
    mac: ENC[AES256_GCM,data:+Z7rf9d+qwtj/mJhwPSo5D0qrAapFZljvqNdWMGiHINZdWRolOwli5VAWjzJPEOddLe3CjuGnBURm650GV3uIF6J+2Lz2QD2cjmGY2kv8n/Kw6kNLsS9fC2l92qkBZR1u00TxyfmyaKEXflhGB6yJ8UtjASlDgpKQpqYhZt1as8=,iv:eVklsqEVmNAqpmW5af7OXUrNqx2s9WuClZYD1NJYfhI=,tag:g70QHPqjhgVfNYUJD9EruA==,type:str]
    version: 3.13.3
