apiVersion: v1
kind: Secret
metadata:
    name: restic-repository
    namespace: backup
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:JGlnnuC1kIscueL4XD5WELRUJqg7nEZyReSgaMwn2u7e9NBGQk0gWNfqN4w=,iv:kMdeyePM/PFr7X5oLP2bHuYmqqBPbPOoXU6iS9gxReA=,tag:KAE7c4zxsYNH5V8+++Etfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNllLMG1KMk9aMCsyS0Rq
            L0ZDOE1ZUlhMS2NvZkdMcGZ2c2s3cUVGNWtrCkhGUnBWQ1dXcU11M2FraVE0TjZn
            Mk5RbUY3R0JZUUtSNGFTQjlqakxCTUEKLS0tIGhPVDVqc0hLRnVhVWRKdlpHTmlV
            U003SEkzQnllTTBmWmJVR3NuN0c2SHcKS2Q7seQ/nEj9kkKPGJsS+n3ebFnaMQjK
            C1taJWNXd95QxJYQqkCgUnFtqjRTqjRmgn2Kys19MgaBWBr2cujlxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcUZCVWt2ckR4bXhaRWV3
            Sy9uQVRjMU1Vb1Nremhab3FBR2JOa2pqaFI0CitteHp6MXQ3c1VJLzB3WjFLeXpQ
            ancxRExXRHU3RVk5NjVDU0pQaEtEdXMKLS0tIGtzTWZOLyt1d3dpdVdDSXdUeWps
            cElvZi80UFVzNkVUVTVyVzhtb3hENUUK97H3itra2Y46caXfYP6migVe52xVuCNE
            jxzowSOx9VnOJ4maP7vuB/ccAxF8HhiKck28oF/Dzp8v1gNjK7xBmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T07:33:14Z"
    mac: ENC[AES256_GCM,data:tW+sgFwGfkCqhtDOqqw9H7knVAvlmJDIs77SNI1S3KdTZM4FfVbrI1ZxX5+fqkCcifpfl9GPPkYCKqw3c0ibSEDHpsK0C1EJDjybK4PA/zO8QBLAJXyHeOLyOYVS2sTHkhOM1FLghEtgv0+je25rITXeWO2+CdysIjjnIhkHgRw=,iv:mOLkzkLfUHv8mw9do4AGKG8N24ehJCd2hLozaUZzHgw=,tag:ZwsPslfpsBYhVbNrJ8yu2A==,type:str]
    version: 3.13.3
