apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: ingress
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:khINpkIIhl1YB5yRkuRsQZFd30CwT+t388w2YlqvHqrdi2QGoE7I7q/T+AeLcTMvNdIRYE5qvqFo5RQ41k4jIkZurfT0tZA8jp5CZa2c1EdIepGT5e3a3pRHAz19r0jXkJWVSHIPUBt0izlw4YdfnrVa92XsAsw5wijjUoVccDCJh2xL5vGXd76BSiRsA+Iy+2tgIGKSWG+D+XJs9Qpkwa6i2GihpW0O5mgfX3sykCLj5AXjb3Bs5g==,iv:pIocUsck3WTrHTJK+oAV00l0ByQ074iIe/D+RFOaSNY=,tag:12/dS3234vDpVI5Y0DTGfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbUtKU0lhSGQ5dVhmcWZG
            N0RWQ0czbmEzUU1LZE5vT2NuQzh4MnVhQkdNCmVUSFBaVCs1WEJVdHNGMEk0N0xU
            TWdMQVhubVIzSVc2eHJuQ0l0NnlDOEUKLS0tIGNURmNCUXltb0NVTFR2a0NPaEE1
            WSt5QzZZT3YzUkduL1JkS1RQQkdCL28Kd6CEjshjmg3qv36UJA2KvmSyRHjmLIzV
            Npcg37bCBvHlv20JxE+oNWpv+xADSEiMnbr07qacMrChEPKbfW5kyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTDNKM1p4Yjdha044N1dO
            RzJtY0xGVCtlR3huakZweTl0Z3pzdDFXRnlvCnBkWHR4clRLVVFseE5PKzNpWklI
            UjM0UHNua3dUZUEzRFlzYUtYV1RkQkUKLS0tIERzRVA0dUZXWDhxK2NUN0FNZlln
            eHBUTW1veU44V2JucURjTTNNTld1VEkKCd/EuZzLjnJOYTd7Utl6I339S5izYyXa
            GEag0vs1y+MjqwHkbxBW8f4xHq3plc47Mqr31bxg3yexdu3K27z2CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T16:39:06Z"
    mac: ENC[AES256_GCM,data:2F32Wti0lVBWh+eHqHQ5vEDYp70RXDO8vKqRpIni3+LypdVpuPDmnOjRvxusaTbE/6+Sz/GBU1MmF9rwIHjoYGty2iy6Omw77aQv7v5Pu1JrVtlApmLw3ddrXNWai1R6U4A4S9FqE50vo05EChqpshFhD0sfiLcQY971pk5HZOU=,iv:hZY4xQv2SLW4bF13m5oSY8g/iG50az3jhgekf9sntzA=,tag:ghnAYVcVCsvnoQAhQHGOGw==,type:str]
    version: 3.13.3
