apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: kube-system
stringData:
    CF_DNS_API_TOKEN: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Ynl6aWF0SFJSblNVNFdG
            Q1hURTJyL25xbG1FRWFhYURWeGJIR21HL0FJCkNOd0Q5ckE2NmNxWkVEQkVrU2xY
            K0xySkgvSGdKd3NraTNXSXpFTVRHYzgKLS0tIGU4VWVxWThhWVJOREhuOVR1OXdS
            MjV1am9IU2dpK2sraWlLTVUreFBiQWMKsoZWeiVgcuM7o7QBusSIPR7XLAMuBFZc
            E1cGMaCfSUvKxC0qtO486XmWY8Fd0SC4E+iWyRqw72QAUYVsjhRv0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRFBRaG43QlhtdFhqb2tw
            N2NvMHNZWFFZdjNuU0ZFTXd4bXdaaGsvMWdRCnd6MXJjSFJ0YUFqemhsTEtWak1S
            WXdzMTVKZHpOSlU2Y2ZZd1hFVGJhQjAKLS0tIGRJeE82UWxBR1BrTHBQUWh5TjVT
            dXNVaVc3YmVISkhHcW5tMGFkYWdIQncKK1tdZbpXZNQ+uopXJfgrq0aCdGPNR9RM
            g6eNTJPfwnRngJdlINKZ7HlIwAaTlkxQC2ONN0mWmVClx/DBLw/PnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T16:15:26Z"
    mac: ENC[AES256_GCM,data:bK4BXjBtA+U9asXn5RcnNnfk6zYkhfg3bCrORP+tH09nRYHf7mbTy49wCWRIj8OswCFeyrYbCu/7FnQnnjXjLZ4oePFG9X4C5+848Pf9lJzu1OVStu8KoG0on0s5MphW8WEK6sc3E/Ji3R7mE1FtYhkzUZyryy1xi4+RTSe6Vq0=,iv:CTMIzR0ff/+NTSKaEiNB7sNrtMn/UwoBbSFilJGy/U8=,tag:97fCk2l3kqyVfHUIVJe3sA==,type:str]
    version: 3.13.3
