apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: ingress
stringData:
    TUNNEL_TOKEN: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjd6a0NvYi93ZU13eDJW
            ZU82N08zMHdSbEZxV0NqZTZQcjBVQXd0enpVClkyOGQzclFvUWpRSWVJOEZRc1c4
            K2wxQkpjSWNFeGtKbys5OUlTcjRtSGcKLS0tIDF3c2x0UFh4R1c3TWZvR3NYck1O
            cjkxTUlKVDM4WUVMc2pPcHVOWlJQcjQKmdgyX3qdO1TlErtx7L8Yb2UdsW2xYefK
            bzTKJYrmSsDIX/hc+f0xHwvNsyzvYq62I8dmzcz/ti30vKC98uzkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWDV1aW9TQ0NmYjVoYXZW
            NFg2QnVveVlraXpORDRNdytjMXdidzc4dXlVCml4cS9JOVkwRno4b1Jjakt4dXA2
            QUl5cUwvTCtPZEdmYzVLS0ZtTHpHalkKLS0tIFBXOVRmQ0I2Y2ZZeDRhWXB4cFRS
            THlDb2VkMEgxUFR0RHFXNXlhT2RVYzAK6LwAP+FQDXHyhFvBcNnXmzYtirarZ9+4
            iQ0cZ+4tQiKHLMvriCq1UgnCzIErs8ZI59CueV0I0cGdvRu1sxYE0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T16:15:26Z"
    mac: ENC[AES256_GCM,data:AMj2PvJLJqp1O6vXDUMfbMbvAUXMBxA67YJir8NAu85Md007P0UW+JEEfVrRHC2A5GtlvnYH0B4+X4D2+EIOUT2vnbBO+UQYByk5WDSQYy+FYMxaRtPYRd9SAHj/S+tOYflp6KxSqD7HpLC2DMdt3G+RI2I9lTK2gQDE2KWdehc=,iv:8vcZ33q+Hd78z3riZATnCpaW4E+whW5Hla8ItVveJtU=,tag:JWH+xDv88Xtjwsczx3jsmQ==,type:str]
    version: 3.13.3
