apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: kube-system
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:vmVZtM+P2qZS24soK++nfxr/++FGisXwL+3w9I/M0k2NGedeKwkjDZbBBp/c8j0Q/EcWQYM=,iv:pk93qLV4nFv27SUCHCn1cmWrH6lStFzVXE7M3MOdGzs=,tag:TTbjqIpy7s5KCIcnFOdA6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNDZPYnhEOWVyMjVYTWhl
            YUhyVmVtWFUyTmdIZEhYd0J0UVJ5ZXhyMXhJCk9hNWxLRnNrSmFVNFFZUER0Y3R1
            QUsxLzBUOXlFblFnUmk3NmRjRDUva3cKLS0tIGJUYytqZFQvenJsRVRsVkt4STAz
            T1FGbjRnVnFraEdjZ3VoNURFVERqWWMKkaLOe5EtUicg2sYwTlyEEHCSP9W9Aycv
            utRzF+WMDjDgD+za0SeYd8KaxzqFvUMLC9fKAXoSfTgj2FOdw/j6rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY0o0eUlCTUh0QVVWa2hw
            NVJFd0hVbmtiVHp1TE4wTXYyOUl4cDRuOVFBCm9MdUNVWGd6K2xydjg1TThacWh6
            SXp6SUo0RUlhZ0MxQ3J1WktQdlVzWkkKLS0tIGJSZnVGRmZwUVU1dU5xdHJNVmZx
            QmlDRnhBdDUxaTVza2V5TGJzUlJOeGMKjLn/7vWPWMjB/YvrbOaxo9A2hBPolJax
            yUkeOVm0vdshByOuMTC1006H9WeLC62grDPOUpikiAKCK3mDEHv8KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T16:34:46Z"
    mac: ENC[AES256_GCM,data:jRMqlAj8aZ3Tdh0PtAWVZU9kMVbAcxY8AIeivfTQm+kNucUZ8xolKKpvIWQIiaoOvoKf/hbZd4qZWNDmpWJwt7JXF3zusCGApcrPYpucHvrelKLj20XLnye1skX7tZghXeTMwOCnzA7FIWaMCgezyOV8J7Gi1OQYh8jhbl+0/cM=,iv:jjsPyYBUAtM+l6za5owkRuGrZB4oqGuZBB8PuCzYMjA=,tag:lKlxFFcUzGG6OHkG2x7i2w==,type:str]
    version: 3.13.3
