apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: kube-system
stringData:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:Y5LaR5AJLWmRKIkEZ4W+hfJhApVStFfHNjywa6wZPdRi9pRGa7YbrlnKj49BKe+6NFE+XTA=,iv:X2Tu0hGewUKGEH7YAsQkDodJ09BP9V/T0FarWcZwPH4=,tag:fXbUAb0DZVz5rMoSsZ/yrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycjAwN0lCQlYxSEJwUkE3
            NTdHOFA5SG9JVytxaitXVDZ4VkJTeEhJV0Y4CjZDVm5zWnJtaDE2QXZYZ3RMUVZy
            M0tsUmFtSWMyT01VWmI4VGNNV2hWZzgKLS0tIHRWVHV5WGxycVNSSWJ4QUEvQTNL
            akZ6Zis5aG5ISE5PalkyOFA2SGZBWkkKZlEFyfNS8lIz3BzaOE5J4+eIaS8wiNyp
            z3gPRlwp1lR/TD7fIpbYf8QGdit6zVigCoTKh7KFHkbNP0NbqyuKxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RytSNWxicjhidUNtQlF6
            ZS92TmxqakZZaE5pMmFMTWlYNlI3aml0K1VZCnFDZ0NDdGxOaUlEVklwQ25keGNu
            SkV0V21aVU8vUDVCVTE1cUZ3YnNsUkEKLS0tIGVQenViMG0rTS9OMTA1bVF4UnVq
            VU01Z1RZRWhyLzVqMUtCTnV3dXh4MjQKLiuzyUqsa5x5Yp+MwT1eP6KsJL44aBda
            2R7SWMOnGydvEZI7zKicn+l1SfPC4M6iEL9yWzkYOlZwImU2hABfZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T16:48:16Z"
    mac: ENC[AES256_GCM,data:HaV482mhgnf5uTIe5RuafcyY4CRAeqvwju/JBDlVKFOa96wctjYJpN4TtbHpIRDndmQ4wr0GhdwEqWntWMr9o1JTJZiRAArNHdx+X0NXMWxWRcmRs2kG0lEZClO/iLPAuAfzLuRGq27UVOp5f6oOYnrgCoA6SUJbwHedoihjohs=,iv:pHs4AoFK3cs/LD2tBgkKOQADkX/kUxfDoYWRtxhAlK4=,tag:UF/AmwTQED2tA7lRwWfGBg==,type:str]
    version: 3.13.3
