apiVersion: v1
kind: Secret
metadata:
    name: ntfy-topic
    namespace: observability
stringData:
    NTFY_TOPIC: ENC[AES256_GCM,data:ZJa9Bf3PsQE6pR3Nio5f7URijFsL9RIk8DhdMgbLlzeaUheI+a4lcvjdOQ0xWcrTwsenXwT3QQ==,iv:EO5jw4eroaqB14IQcyWMDR8xx5hpeiVdVQXUZIWFwiQ=,tag:URrNlHanS/xZyLT7UgQ3/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ3MybjZrS2xrbys4Y0kw
            QjQ4WFlYVzVyaTZWcjNHbUM2bGxvN0x6a0ZzClpuaGRCdEQxWUhGaEgvTkFyZWF2
            RkRHcTdlVGkwWlFFTDRBZmFwWGNtRE0KLS0tIGhxNEZzWGVUZ21PaXV1ZmNiUTdR
            NUticThLWks2NEFkTm5WdmV1Y2dlSTgKFEuzclfuuHiM8BsTxREQNpFUbLk462qL
            ZTbRWZOi6YztXxrhPUubv9edBYVz6XpDLhL6ShPaWWc4R48z67W3fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MC9EeUl0V2FqajVWU3lz
            TDZzWEpPSDBIdEZjekNucGtHZ1AzTDBhV0JRCjUrMm5lRmpIUTA4SjJMQ3g2bjVS
            akl3cDRzdDljWnBLYzVQS3g4UHcvUnMKLS0tIFNIb0M5TStpTURZZzViemJTV20w
            ejJzWkNHZm5kKy94amYrMGI0VE05NTgKoKD9D/dIxD6LsK2PcQHGG/ISzh6qYkZR
            JwwQDi0UYOaiJ4cEU5ucba0uYfCzjNIILZ4ZyQHNKrbabj+6dB5sYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T21:05:25Z"
    mac: ENC[AES256_GCM,data:1zYXbRn5aKV3/hc4MncbOHSo+L3+zd6gPt43TtXtwUj90arvclRIXoDtVeURwGT6VXpAIE9PBcsba8h3bYQpl3Ttez/9vKXerpkOtI2pHAZ3AWfnylismMw3nKcE79A7dDMettbqqMX88IqIowjsU1d4p6FE6zCQmBYSqPJFuVM=,iv:YYekWdZCIrmSWHEfA3FrC7BxhnApFFsezdiaD7Kb6zs=,tag:IczuoQObPjFqZZYIrws9IA==,type:str]
    version: 3.13.3
