apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres
    namespace: immich
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:lncRBD3e,iv:zY9S4yD/uzaC6dAlhsBFm5pezdzOlK2VEceChcrh69c=,tag:yz6ZSMS2q2glleULhEGYqQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:KtTiMDvG,iv:Fky8rIEA8BTNuzrnR1iMIc7SchJtsyrLJO+xpenl7Ow=,tag:Wvl2CcAxqg1e/hNpC+xHlQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:pKE6cyuCq4dOyabO3kzLbAkGI93f/yyO0vq11NubhYc=,iv:Bl9/3znlfijNjR3zN0RsVfW+huj//IrSr07BNYmI8a8=,tag:sekKMT5m6vM6+i79ChsiFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VmZEaXBieXJTQ1c4dndJ
            T1VHK1RzVEtIQmJXNm5PQkxnZENHSnhGeFFFCnFWWGptUk9EaHpmOERuWFhiU05m
            L24vQmhFSGtoQUVNSldSdTNpeVdEUmsKLS0tIEtNN3NOQitCUkdpd1A0M3FDVFFk
            UllOZ2p4eU80WGptbjh1aDYrRUlzeE0KMFvrl7jCjaY7jp+dyJ2TnaBPaOziBdUK
            huNVHWaymqJO0F3bpa0sX2PvnjQTX56uS0cb4louNbcPX7a3/uTdYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsejNPL25sOGdQbjNlQlRG
            OHBVeGdtcXN3dVkyc2xHRE80M3hSYjBCQWpRClhvQmM1UWdRR25jMkoyd1ZxMVcz
            VWMyNHUvTFFVYXJncU5SU3gvZHRJVlEKLS0tIGhSWFRwQUhzSTg2Z0V3SzljdlIx
            anM0RXZPb1Q0Y09JbDR2QTYxTU1TL1EK/cIQopNIhNu2SQtAbkCM9NCuH9hWD0sU
            MfV+QNKlAGFtYXqbDpnkXsWjmYdQFPSVW196GWKWhITNDrrZU1gW2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T10:09:38Z"
    mac: ENC[AES256_GCM,data:LQKsTnok1v5p/KTHAoYMq6ooYdhbWZA1jD8vKs/bAu8HpQKzSt91zCUMI4XS/yT2D4WZlAHzOH8DnTHu7w/dmmsLFZzoFfbxpiCWf86BYKQS2/DouSfUz+bhjs+fuVhEp7JADoRtyL1nljJWdiq6waymZILjJoln7SKZDpyajYU=,iv:9llbO+Kjs/qyT9AXnfR0b/4kSPKOyVcu6CgOCfF/hGM=,tag:1gZt2+A+47CoduQiTuGCmQ==,type:str]
    version: 3.13.3
