apiVersion: v1
kind: Secret
metadata:
    name: sops-age-smoke-test
    namespace: default
stringData:
    ping: ENC[AES256_GCM,data:EuNYEQ==,iv:zATslo0JUj2P4usA+9Z8rFY38Kz7xy0kZGKZMIyBswA=,tag:ki63+KjDGVLlQJfGXbBXLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WDQrTlpjV0loL0swbmRn
            RzBTdjkycnNWRmlUN1NpdVYxUWcyMWozUkZZCkU1VmtWZ3JETXhINmpzdDdRS2Ni
            cFRZbXlmcGFXcHFoV2htVitsbGtVaVEKLS0tIE9EYVMzMGEyWEhCTkZNd0o0QldF
            SHg2MmkwRWhYVG9LdTBaNEw5dDZJRzQKfszx5vmfS6TJOSPoUbX7cZEU+K8N2K0N
            0q00qpYenppabtzkUSMu8Z0AKvn/B70x0z2+7lbwZT74ZrMbxj50wA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12sk58zgt3hszlrjdm97p35swaeww0mnujj2a9dx6ys965r2neejqdu35en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVk93SDBqek5uNU5ldGNr
            Vit4L2ZvQjgxK3ZHdVpCQW9XQjhLUTRQU0YwCkhVOFh4RzJ1aWRCVVNETDZFQjR5
            cFVCMDV0SE56SDhJaDNXY2Q1NVhQd0EKLS0tIEZLRmx5VWE3TjBWTFJUbXVsaG94
            QmRlMVltVko4THpLN3BRaUlRcW8wMFkKxqSlVNzZ/WdenEO/r8w39PwzB/60MBd5
            GuUNId549BvuR8Az6u2mw/m30G1/SoTHN0l43+HquaglRWYFxT5KRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa86n7jlsa0fe7tjknm5avxptuqepnlqzej5f74r9aetpunvz3xswhzner
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T07:41:14Z"
    mac: ENC[AES256_GCM,data:jojjxVfuFlxZvBtWXV1yN4VoCT348SUBy8gpJbvPgnSDApZVNg6YN2ItCVPJ4qwPdf4T7vVzg6juO3m+JKMTtLKkh2w0YKE1eFvXTSEAk6HCvuyYKvzO9D+QYKtaZWBCLoSpo2G7SNgxXkw/MCcDIYB/Tb4x+tO5dxtt+zX8XoY=,iv:1575KzZB3qb1PM+1SRRZLg1nhjbc+akAnItlD80Ulg0=,tag:nSWWWFtRDvkBM7qBvSAnDQ==,type:str]
    version: 3.13.3
